<a href="https://colab.research.google.com/github/parth111999/Breast-Cancer-Detection-System/blob/main/Breast_Cancer_Detection_System.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [28]:
# Importing Pandas for DataFrame & Numpy for numerics calculation
import pandas as pd
import numpy as np

# Importing sklearn for Dataset & Preprocessing the Data
from sklearn.datasets import load_breast_cancer
from sklearn.preprocessing import StandardScaler

# Importing Keras for initializing Deep Learning Model
from keras.models import Sequential
from keras.layers import Dense

In [29]:
# Load the dataset
data = load_breast_cancer()
data

{'DESCR': '.. _breast_cancer_dataset:\n\nBreast cancer wisconsin (diagnostic) dataset\n--------------------------------------------\n\n**Data Set Characteristics:**\n\n    :Number of Instances: 569\n\n    :Number of Attributes: 30 numeric, predictive attributes and the class\n\n    :Attribute Information:\n        - radius (mean of distances from center to points on the perimeter)\n        - texture (standard deviation of gray-scale values)\n        - perimeter\n        - area\n        - smoothness (local variation in radius lengths)\n        - compactness (perimeter^2 / area - 1.0)\n        - concavity (severity of concave portions of the contour)\n        - concave points (number of concave portions of the contour)\n        - symmetry \n        - fractal dimension ("coastline approximation" - 1)\n\n        The mean, standard error, and "worst" or largest (mean of the three\n        largest values) of these features were computed for each image,\n        resulting in 30 features.  For

In [30]:
# Keys in the dataset
data.keys()

dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names', 'filename'])

In [31]:
print(data["DESCR"])

.. _breast_cancer_dataset:

Breast cancer wisconsin (diagnostic) dataset
--------------------------------------------

**Data Set Characteristics:**

    :Number of Instances: 569

    :Number of Attributes: 30 numeric, predictive attributes and the class

    :Attribute Information:
        - radius (mean of distances from center to points on the perimeter)
        - texture (standard deviation of gray-scale values)
        - perimeter
        - area
        - smoothness (local variation in radius lengths)
        - compactness (perimeter^2 / area - 1.0)
        - concavity (severity of concave portions of the contour)
        - concave points (number of concave portions of the contour)
        - symmetry 
        - fractal dimension ("coastline approximation" - 1)

        The mean, standard error, and "worst" or largest (mean of the three
        largest values) of these features were computed for each image,
        resulting in 30 features.  For instance, field 3 is Mean Radius, f

In [32]:
# 569 rows (entries) & 30 Columns (input)
data["data"].shape

(569, 30)

In [33]:
data["data"][0]

array([1.799e+01, 1.038e+01, 1.228e+02, 1.001e+03, 1.184e-01, 2.776e-01,
       3.001e-01, 1.471e-01, 2.419e-01, 7.871e-02, 1.095e+00, 9.053e-01,
       8.589e+00, 1.534e+02, 6.399e-03, 4.904e-02, 5.373e-02, 1.587e-02,
       3.003e-02, 6.193e-03, 2.538e+01, 1.733e+01, 1.846e+02, 2.019e+03,
       1.622e-01, 6.656e-01, 7.119e-01, 2.654e-01, 4.601e-01, 1.189e-01])

In [34]:
data["target"]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,

In [62]:
j = 0 
for i in data["feature_names"]:
  print(i,":",data["data"][0][j])
  j +=1

mean radius : 17.99
mean texture : 10.38
mean perimeter : 122.8
mean area : 1001.0
mean smoothness : 0.1184
mean compactness : 0.2776
mean concavity : 0.3001
mean concave points : 0.1471
mean symmetry : 0.2419
mean fractal dimension : 0.07871
radius error : 1.095
texture error : 0.9053
perimeter error : 8.589
area error : 153.4
smoothness error : 0.006399
compactness error : 0.04904
concavity error : 0.05373
concave points error : 0.01587
symmetry error : 0.03003
fractal dimension error : 0.006193
worst radius : 25.38
worst texture : 17.33
worst perimeter : 184.6
worst area : 2019.0
worst smoothness : 0.1622
worst compactness : 0.6656
worst concavity : 0.7119
worst concave points : 0.2654
worst symmetry : 0.4601
worst fractal dimension : 0.1189


In [36]:
feature = data["data"]
label = data["target"]

In [37]:
# StandardScalar Function
scale = StandardScaler()
feature = scale.fit_transform(feature)
feature

array([[ 1.09706398, -2.07333501,  1.26993369, ...,  2.29607613,
         2.75062224,  1.93701461],
       [ 1.82982061, -0.35363241,  1.68595471, ...,  1.0870843 ,
        -0.24388967,  0.28118999],
       [ 1.57988811,  0.45618695,  1.56650313, ...,  1.95500035,
         1.152255  ,  0.20139121],
       ...,
       [ 0.70228425,  2.0455738 ,  0.67267578, ...,  0.41406869,
        -1.10454895, -0.31840916],
       [ 1.83834103,  2.33645719,  1.98252415, ...,  2.28998549,
         1.91908301,  2.21963528],
       [-1.80840125,  1.22179204, -1.81438851, ..., -1.74506282,
        -0.04813821, -0.75120669]])

In [38]:
# Print all the feature with its value
j = 0
for i in data['feature_names']:
  print(i,":",feature[0][j])
  j+=1

mean radius : 1.0970639814699807
mean texture : -2.0733350146975935
mean perimeter : 1.2699336881399383
mean area : 0.9843749048031144
mean smoothness : 1.568466329243428
mean compactness : 3.2835146709868264
mean concavity : 2.652873983743168
mean concave points : 2.532475216403245
mean symmetry : 2.2175150059646405
mean fractal dimension : 2.255746885296269
radius error : 2.4897339267376193
texture error : -0.5652650590684639
perimeter error : 2.833030865855184
area error : 2.4875775569611043
smoothness error : -0.21400164666895383
compactness error : 1.3168615683959484
concavity error : 0.72402615808036
concave points error : 0.6608199414286064
symmetry error : 1.1487566671861758
fractal dimension error : 0.9070830809973359
worst radius : 1.8866896251792757
worst texture : -1.3592934737640827
worst perimeter : 2.3036006236225606
worst area : 2.0012374893299207
worst smoothness : 1.3076862710715387
worst compactness : 2.616665023512603
worst concavity : 2.1095263465722556
worst conca

In [39]:
# Demo Data Check
print(feature[0])
print(data['target_names'][label[0]],label[0])

[ 1.09706398 -2.07333501  1.26993369  0.9843749   1.56846633  3.28351467
  2.65287398  2.53247522  2.21751501  2.25574689  2.48973393 -0.56526506
  2.83303087  2.48757756 -0.21400165  1.31686157  0.72402616  0.66081994
  1.14875667  0.90708308  1.88668963 -1.35929347  2.30360062  2.00123749
  1.30768627  2.61666502  2.10952635  2.29607613  2.75062224  1.93701461]
malignant 0


In [40]:
pd.DataFrame(feature, columns = data["feature_names"]).head()

mean radius  mean texture  ...  worst symmetry  worst fractal dimension
0     1.097064     -2.073335  ...        2.750622                 1.937015
1     1.829821     -0.353632  ...       -0.243890                 0.281190
2     1.579888      0.456187  ...        1.152255                 0.201391
3    -0.768909      0.253732  ...        6.046041                 4.935010
4     1.750297     -1.151816  ...       -0.868353                -0.397100

[5 rows x 30 columns]

In [41]:
pd.DataFrame(label, columns = ["label"]).head()

label
0      0
1      0
2      0
3      0
4      0

In [42]:
df_frt = pd.DataFrame(feature, columns = data["feature_names"])
df_lbl = pd.DataFrame(label, columns = ["label"])
# Concatenation of Features & Label  
df = pd.concat([df_frt,df_lbl], axis = 1)
# Shuffle the Rows
df = df.sample(frac = 1)

feature = df.values[ : , : 30]
label = df.values[ : ,30: ]

df

mean radius  mean texture  ...  worst fractal dimension  label
496    -0.419572     -0.260550  ...                 1.072528      1
469    -0.712106     -0.258223  ...                 0.485120      1
259     0.398389      3.320807  ...                 2.020138      0
244     1.497524      0.979777  ...                -0.432566      0
105    -0.288925     -0.867914  ...                 3.133996      0
..           ...           ...  ...                      ...    ...
348    -0.754709     -0.758542  ...                 0.204162      1
168     0.949377      1.254371  ...                 0.501745      0
106    -0.706426     -0.223317  ...                 0.389251      1
375     0.580158     -0.749234  ...                 0.313331      1
98     -0.717787     -1.500877  ...                 0.200283      1

[569 rows x 31 columns]

In [43]:
# 500 Training Data

X_train = feature[:500]
y_train = label[:500]

# 35 Validation Data

X_val = feature[500:35]
y_val = label[500:35]

# 34 Testing Data

X_test = feature[535:]
y_test = label[535:]

In [44]:
# Initializing Deep Learning Model
model = Sequential()

model.add(Dense(32, activation = "relu",input_dim = 30))
model.add(Dense(15, activation = "relu"))
model.add(Dense(8, activation = "relu"))
model.add(Dense(4, activation = "relu"))
model.add(Dense(1, activation = "sigmoid"))

model.compile(loss = "binary_crossentropy", optimizer = "adam", metrics = ["accuracy"])


In [45]:
# Training the Data
model.fit(X_train,y_train, epochs = 10, batch_size = 1, validation_data = (X_val,y_val))

Epoch 1/10
500/500 [==============================] - 1s 2ms/step - loss: 0.2300 - accuracy: 0.9160
Epoch 2/10
500/500 [==============================] - 1s 2ms/step - loss: 0.0801 - accuracy: 0.9800
Epoch 3/10
500/500 [==============================] - 1s 1ms/step - loss: 0.0503 - accuracy: 0.9780
Epoch 4/10
500/500 [==============================] - 1s 1ms/step - loss: 0.0436 - accuracy: 0.9800
Epoch 5/10
500/500 [==============================] - 1s 1ms/step - loss: 0.0235 - accuracy: 0.9900
Epoch 6/10
500/500 [==============================] - 1s 1ms/step - loss: 0.0398 - accuracy: 0.9840
Epoch 7/10
500/500 [==============================] - 1s 1ms/step - loss: 0.0217 - accuracy: 0.9920
Epoch 8/10
500/500 [==============================] - 1s 1ms/step - loss: 0.0161 - accuracy: 0.9940
Epoch 9/10
500/500 [==============================] - 1s 1ms/step - loss: 0.0158 - accuracy: 0.9920
Epoch 10/10
500/500 [==============================] - 1s 1ms/step - loss: 0.0133 - accuracy: 0.9960

In [46]:
# Check the Test Data Accuracy
model.evaluate(X_test,y_test)

2/2 [==============================] - 0s 7ms/step - loss: 0.2180 - accuracy: 0.9706


[0.21797902882099152, 0.970588207244873]

In [47]:
sample = X_test[24]
# Converting the sample into multidimensional Array for Prediction
sample = np.reshape(sample,(1,30))

In [48]:
# Single Row Prediction
if model.predict(sample) > 0.5:
  print("Benign Tumor")
else:
  print("Malignant Tumor")

Benign Tumor


In [49]:
# Actual Value
'''
0 - Malignant Tumor
1 - Benign Tumor
'''
int(y_test[24])

1

In [50]:
# Predicting the Tumor (Multiple Rows)
'''
"-" = Predicted Tumor
"*" = Actual Value
'''
for i in range(25,34):
  sample = X_test[i]
  sample = np.reshape(sample,(1,30))

  if model.predict(sample) > 0.5:
    print("- Benign Tumor")
  else:
    print("- Malignant Tumor")
  
  if y_test[i] == 0:
    print("* Malignant Tumor")
  else:
      print("* Benign Tumor")
  print("---------------------")


- Benign Tumor
* Benign Tumor
---------------------
- Benign Tumor
* Benign Tumor
---------------------
- Malignant Tumor
* Malignant Tumor
---------------------
- Benign Tumor
* Benign Tumor
---------------------
- Benign Tumor
* Benign Tumor
---------------------
- Malignant Tumor
* Malignant Tumor
---------------------
- Benign Tumor
* Benign Tumor
---------------------
- Benign Tumor
* Benign Tumor
---------------------
- Benign Tumor
* Benign Tumor
---------------------
